apiVersion: v1
kind: Pod
metadata:
  name: buildah-demo
  namespace: imgbuild
  labels:
    app: buildah-demo
spec:
  restartPolicy: Never
  containers:
    - name: buildah-demo
      # 使用 Buildah 官方镜像
      image: quay.io/buildah/stable:latest
      # 保持容器运行，等待手动触发
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "容器已启动，等待文件复制..."
          echo "文件复制完成后，请执行: kubectl -n imgbuild exec buildah-demo -- /workspace/main"
          # 配置 rootless 模式
          mkdir -p /root/.config/containers
          echo '[storage]' > /root/.config/containers/storage.conf
          echo 'driver = "overlay"' >> /root/.config/containers/storage.conf
          echo '[storage.options]' >> /root/.config/containers/storage.conf
          echo 'mount_program = "/usr/bin/fuse-overlayfs"' >> /root/.config/containers/storage.conf
          # 保持容器运行
          tail -f /dev/null
      volumeMounts:
        - name: workspace
          mountPath: /workspace
      # Rootless 模式配置
      securityContext:
        allowPrivilegeEscalation: false
        # 注意：Buildah rootless 模式在 K8s 中的权限要求
        # 1. 理论上不需要 SYS_ADMIN（使用 fuse-overlayfs）
        # 2. 但需要访问 /dev/fuse 设备
        # 3. 在 K8s 中，访问设备通常需要 privileged 或 SYS_ADMIN
        # 4. 如果使用 vfs 存储驱动，则不需要挂载，但性能较差
        # 当前配置：尝试不使用 SYS_ADMIN，如果失败则添加
        capabilities:
          add:
            - SYS_ADMIN  # 在 K8s 中通常需要，用于挂载文件系统（详见 ROOTLESS_NOTES.md）
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "1000m"
  volumes:
    - name: workspace
      emptyDir: {}

